# This is a basic workflow to help you get started with Actions

name: Release Build

on:
  push:
    tags: [ '*' ]

jobs:
  build_release_mingwX64:
    name: Build Release on Windows Server 2019
    runs-on: windows-2019
    steps:
    - name: Setup Java JDK
      id: setup-jdk-windows-x64
      uses: actions/setup-java@v1.4.1
      with:
        java-version: 11
    - name: Checkout Repository
      id: checkout-windows-x64
      uses: actions/checkout@v2
    - name: Gradle Link
      id: link-windows-x64
      shell: cmd
      run: call .\gradlew.bat linkReleaseExecutableMingwX64
    - name: Upload Release Executable
      uses: actions/upload-artifact@v2.1.4
      with:
        name: knative-vm-windows-x64.exe
        path: build/bin/mingwX64/releaseExecutable/knative-vm.exe
        
  build_release_linuxX64:
    name: Build Release on Ubuntu 18.04
    runs-on: ubuntu-18.04
    steps:
    - name: Setup Java JDK
      id: setup-jdk-linux-x64
      uses: actions/setup-java@v1.4.1
      with:
        java-version: 11
    - name: Checkout Repository
      id: checkout-linux-x64
      uses: actions/checkout@v2
    - name: Grant execute permission for gradlew
      id: chmod-gradle-linux-x64
      run: chmod +x gradlew
    - name: Gradle Link
      id: link-linux-x64
      run: ./gradlew linkReleaseExecutableLinuxX64
    - name: Upload Release Executable
      uses: actions/upload-artifact@v2.1.4
      with:
        name: knative-vm-linux-x64.kexe
        path: build/bin/linuxX64/releaseExecutable/knative-vm.kexe

  create_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build_release_mingwX64, build_release_linuxX64]
    steps:
    - name: Create Release
      id: create-release
      uses: actions/create-release@v1.1.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Automated Release by GitHub Action CI
        draft: false
        prerelease: true
    - name: Download all Build Artifacts
      uses: actions/download-artifact@v2.0.5        
      with:
        path: ./      
    - name: Upload Release Asset (Windows x64)
      id: upload-release-asset-windows-x64
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: /home/runner/work/kotlin-native-vm/kotlin-native-vm/knative-vm-windows-x64.exe
        asset_name: knative-vm-windows-x64.exe
        asset_content_type: application/x-executable
    - name: Upload Release Asset (Linux x64)
      id: upload-release-asset-linux-x64
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: /home/runner/work/kotlin-native-vm/kotlin-native-vm/knative-vm-linux-x64.kexe
        asset_name: knative-vm-linux-x64.kexe
        asset_content_type: application/x-executable

