# This is a basic workflow to help you get started with Actions

name: Release Build

on:
  push:
    tags: [ '*' ]

jobs:
  create_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
    - name: Create Release
      id: create-release
      uses: actions/create-release@v1.1.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Automated Release by GitHub Action CI
        draft: false
        prerelease: true
  build_release_mingwX64:
    name: Build Release on Windows Server 2019
    runs-on: windows-2019
    steps:
    - name: Setup Java JDK
      id: setup-jdk-windows-x64
      uses: actions/setup-java@v1.4.1
      with:
        java-version: 11
    - name: Checkout Repository
      id: checkout-windows-x64
      uses: actions/checkout@v2
    - name: Gradle Assemble
      id: assemble-windows-x64
      shell: cmd
      run: call .\gradlew.bat assemble
    - name: Upload Release Asset (Windows x64)
      id: upload-release-asset-windows-x64
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ jobs.create_release.steps.create-release.outputs.upload_url }}
        asset_path: build/bin/mingwX64/releaseExecutable/knative-vm.exe
        asset_name: knative-vm-windows-x64.exe
        asset_content_type: application/x-executable
  build_release_linuxX64:
    name: Build Release on Ubuntu 18.04
    runs-on: ubuntu-18.04
    steps:
    - name: Setup Java JDK
      id: setup-jdk-linux-x64
      uses: actions/setup-java@v1.4.1
      with:
        java-version: 11
    - name: Checkout Repository
      id: checkout-linux-x64
      uses: actions/checkout@v2
    - name: Gradle Assemble
      id: assemble-linux-x64
      run: ./gradlew assemble
    - name: Upload Release Asset (Linux x64)
      id: upload-release-asset-linux-x64
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ jobs.create_release.steps.create-release.outputs.upload_url }}
        asset_path: build/bin/linuxX64/releaseExecutable/knative-vm.kexe
        asset_name: knative-vm-linux-x64.kexe
        asset_content_type: application/x-executable
#  build_release_macosX64:
#    name: Build Release on macOS Catalina 10.15
#    runs-on: macos-10.15
#    steps:
#    - name: Setup Java JDK
#      id: setup-jdk-macos-x64
#      uses: actions/setup-java@v1.4.1
#      with:
#        java-version: 11
#    - name: Checkout Repository
#      id: checkout-macos-x64
#      uses: actions/checkout@v2
#    - name: Gradle Assemble
#      id: assemble-macos-x64
#      run: ./gradlew assemble
#    - name: Upload Release Asset (macOS x64)
#      id: upload-release-asset-macos-x64
#      uses: actions/upload-release-asset@v1.0.2
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      with:
#        upload_url: ${{ jobs.create_release.steps.create-release.outputs.upload_url }}
#        asset_path: build/bin/macosX64/releaseExecutable/knative-vm.kexe
#        asset_name: knative-vm-linux-x64.kexe
#        asset_content_type: application/x-executable

